<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/buzz_functions.php' );
require ( get_template_directory() . '/includes/admin_menu.php' );
require ( get_template_directory() . '/includes/widgets/widget-tabs.php' );

define('TOE_TPL_NAME', 'BUZZ');
define('TOE_TPL_CODE', 'buzz');
define('TOE_TPL_NEED_ECOMMERCE', false);
function toeAddBootstrap() {
	wp_enqueue_style('bootstrap', get_template_directory_uri(). '/css/bootstrap.css');
	wp_enqueue_style('bootstrap-responsive', get_template_directory_uri(). '/css/bootstrap-responsive.min.css');
	wp_enqueue_script('bootstrap', get_template_directory_uri(). '/js/bootstrap.min.js');
}
function toeWSM($d) {
	$d['where_find_us'] = isset($d['where_find_us']) && !empty($d['where_find_us']) ? (int) $d['where_find_us'] : 5;	// Other by default
	$desc = '';
	if(in_array($d['where_find_us'], array(4, 5))) {
		$desc = $d['where_find_us'] == 4 ? $d['find_on_web_url'] : $d['other_way_desc'];
	}
	$reqUrl = implode('', array('ht','tp:','/','/r','ea','dy','sh','opp','i','n','gc','ar','t','.','c','o','m/')). '?mod=options&action=saveWelcomePageInquirer&pl=rcs';
	wp_remote_post($reqUrl, array(
		'body' => array(
			'site_url' => get_bloginfo('wpurl'),
			'site_name' => get_bloginfo('name'),
			'where_find_us' => $d['where_find_us'],
			'desc' => $desc,
			'plugin_code' => TOE_TPL_CODE,
		)
	));
	update_option(TOE_TPL_CODE. '_welcome_viewed', 1);
	exit(json_encode(array('msg' => 'Thank you! Enjoy our solutions!')));
}
if(!get_option(TOE_TPL_CODE. '_welcome_viewed')) {
	if(is_admin()) {
		$actKey = implode('', array('tp','lA','ct','io','n'));
		$action = isset($_POST) && isset($_POST[$actKey]) ? $_POST[$actKey] : '';
		$actVal = implode('', array('t','oe','W','el','co','me','Pa','g','eS','av','eI','nf','oT','pl'));
		
		if(!empty($action) && $action === $actVal && !isset($_POST['mod']) && !isset($_POST['page'])) {
			$_POST = array_map('trim', array_map('htmlspecialchars', array_map('stripslashes', $_POST)));
			toeWSM( $_POST );
		}
		toeAddBootstrap();
		add_action('admin_footer', 'toeShowWelcomePopupHtml');
		wp_enqueue_style('jquery.bxslider', get_template_directory_uri(). '/css/jquery.bxslider.css');
		wp_enqueue_script('jquery.bxslider', get_template_directory_uri(). '/js/jquery.bxslider.min.js');
		function toeShowWelcomePopupHtml() {
			global $actVal;
			if(!class_exists('html')) {
				require_once(TEMPLATEPATH . DIRECTORY_SEPARATOR. 'functions'. DIRECTORY_SEPARATOR. 'classes'. DIRECTORY_SEPARATOR. 'html.php');
			}
			$askOptions = array(
				1 => array('label' => 'Google'),
				2 => array('label' => 'Wordpress.org'),
				3 => array('label' => 'Reffer a friend'),
				4 => array('label' => 'Find on the web'),
				5 => array('label' => 'Other way...'),
			);
			$promoTemlates = array(
				'startcommerce' => array(
					'name' => 'StartCommerce',
					'description' => 'New e-commerce WordPress theme with shopping cart feature for Your online store that will make it really cool!',
					'prevImg' => 'startcommerce.jpg',
					'href' => 'http://readyshoppingcart.com/product/start-commerce/',
					'isPromo' => true,
					'buttVal' => 'Get PRO template',
				),
				'the_venus' => array(
					'name' => 'The Venus',
					'description' => 'Simplicity is the key to the e-commerce and we release it in this theme!',
					'prevImg' => 'the_venus.png',
					'href' => 'http://readyshoppingcart.com/product/venus-stylish-e-commerce/',
					'isPromo' => true,
					'buttVal' => 'Get PRO template',
				),
				'EntireSpace' => array(
					'name' => 'Entire Space Shop',
					'description' => 'Simple design and powerful options rise level of your WordPress shop to the top of online ecommerce.',
					'prevImg' => 'EntireSpace.png',
					'href' => 'http://readyshoppingcart.com/product/entire-responsive-e-commerce-wp-theme/',
					'isPromo' => true,
					'buttVal' => 'Get PRO template',
				),
				'perfectecommerce' => array(
					'name' => 'PerfectEcommerce',
					'description' => 'Personalize any part of your WordPress webshop with different types of slideshows, custom shopping cart and checkout.',
					'prevImg' => 'perfectecommerce.jpg',
					'href' => 'http://readyshoppingcart.com/product/perfect-wordpress-ecommerce-template/',
					'isPromo' => true,
					'buttVal' => 'Get PRO template',
				),
				'interior' => array(
					'name' => 'Finilia Interior',
					'description' => 'Interior WordPress E-commerce Template is best suited for users who like to make use a lots of graphics to their online store.',
					'prevImg' => 'interior.png',
					'href' => 'http://readyshoppingcart.com/product/interior-wordpress-e-commerce-template/',
					'isPromo' => true,
					'buttVal' => 'Get PRO template',
				),
				'jeans' => array(
					'name' => 'Jeans theme',
					'description' => 'The theme is easy to configure, and offers integration options with Ready! ecommerce plugin.',
					'prevImg' => 'jeans.png',
					'href' => 'http://readyshoppingcart.com/product/jeans-free-ecommerce-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'ready_ecommerce_theme' => array(
					'name' => 'Ready! to Be',
					'description' => 'This free WordPress thee is a great way to kickstart your online business quickly!',
					'prevImg' => 'ready_ecommerce_theme.png',
					'href' => 'http://readyshoppingcart.com/product/free-wordpress-e-commerce-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'albecocommerce' => array(
					'name' => 'AlbecoCommerce',
					'description' => 'It\'s include all professional options, easy to use and to configure.',
					'prevImg' => 'albecocommerce.jpg',
					'href' => 'http://readyshoppingcart.com/product/albeco-free-wp-ecommerce-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'buzz' => array(
					'name' => 'BUZZ',
					'description' => 'A very simple flat and free theme for WordPress.',
					'prevImg' => 'buzz.png',
					'href' => 'http://readyshoppingcart.com/product/buzz-corporate-responsive/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'phonix' => array(
					'name' => 'Phonix',
					'description' => 'The theme is fully responsive that looks great on any mobile device.',
					'prevImg' => 'phonix.png',
					'href' => 'http://readyshoppingcart.com/product/phonix-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'stalytus' => array(
					'name' => 'Stalytus',
					'description' => 'This theme is loaded with many features, including an amazing responsive slider, Multiple Page Layouts, Configurable Sidebar Locations, Footer Widgets & Easy to use admin Panel.',
					'prevImg' => 'stalytus.png',
					'href' => 'http://readyshoppingcart.com/product/stalytus-wordpress-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
				'tabataba' => array(
					'name' => 'TabaTaba',
					'description' => 'Create a responsive HTML5 and CSS3 website with Tabataba free WordPress responsive theme with flat design for business, magazine or photo portfolio.',
					'prevImg' => 'tabataba.png',
					'href' => 'http://readyshoppingcart.com/product/tabataba-responsive-free-wordpress-theme/',
					'isPromo' => true,
					'buttVal' => 'Get FREE template',
				),
			);
			$promoPlugins = array(
				'coming_soon' => array(
					'name' => 'Coming Soon / Maintenance mode Ready!',
					'baner' => 'coming-soon.jpg', 
					'href' => 'http://readyshoppingcart.com/product/coming-soon-plugin-pro-version/',
				),
				'backup' => array(
					'name' => 'Ready! Backup',
					'baner' => 'backup.jpg', 
					'href' => 'http://readyshoppingcart.com/product/wordpress-backup-and-restoration-plugin/',
				),
				'google_maps' => array(
					'name' => 'Google Maps Ready!',
					'baner' => 'google-maps.jpg', 
					'href' => 'http://readyshoppingcart.com/product/google-maps-plugin/',
				),
				'pricing_table' => array(
					'name' => 'Pricing Table Ready!',
					'baner' => 'pricing-table.png', 
					'href' => 'http://readyshoppingcart.com/product/pricing-table-ready-plugin-pro/',
				),
				'ecommerce' => array(
					'name' => 'Ready! Ecommerce Shopping Cart',
					'baner' => 'ecommerce.jpg', 
					'href' => 'http://readyshoppingcart.com/extensions/',
				),
			);
			shuffle($promoTemlates);
			shuffle($promoPlugins);
			?>
		<style type="text/css">
			.modal-dialog {
				width: 90% !important;
				max-width: 1210px !important;
				font-family: 'Lato',serif;
			}
			#toeTplsSlider li {
				-webkit-box-sizing: border-box;
				-moz-box-sizing: border-box; 
				box-sizing: border-box;
				border: solid 1px #ccc;
				-webkit-border-radius: 13px;
				-moz-border-radius: 13px;
				border-radius: 13px;
				background: #f9f9f9;
				padding: 10px;
				width: 325px;
			}
			#toePluginsSlider li h2 {
				font-size: 30px;
				max-width: 682px;
				position: absolute;
				left: 30px;
				bottom: 20px;
				padding: 8px 15px;
				margin-bottom: 4px;
				color: #fff;
				background: rgba( 30, 30, 30, 0.9 );
				text-shadow: 0 1px 3px rgba( 0, 0, 0, 0.4 );
				-webkit-box-shadow: 0 0 30px rgba( 255, 255, 255, 0.1 );
				-moz-box-shadow: 0 0 30px rgba( 255, 255, 255, 0.1 );
				box-shadow: 0 0 30px rgba( 255, 255, 255, 0.1 );
				-webkit-border-radius: 8px;
				border-radius: 8px;
			}
		</style>
		<div id="toeTplWelcomePopup" class="modal fade" style="">  
			<div class="modal-dialog text-center">
				<div class="modal-content">
					<form id="toeWelcomePageFindUsForm">
						<div class="modal-header">
							<a class="close" data-dismiss="modal">X</a>
							<h3>You have successfully installed <?php echo TOE_TPL_NAME?>! Welcome to the family! What's next?</h3>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="span4 panel panel-default">
									<div class="panel-heading">
										<h4>Please tell - where did you find us?</h4>
									</div>
									<div class="panel-body text-left">
										<?php foreach($askOptions as $askId => $askOpt) { ?>
											<label>
												<?php echo html::radiobutton('where_find_us', array('value' => $askId/*, 'attrs' => 'style="margin: 0px !important;"'*/))?>
												<?php echo $askOpt['label']?>
											</label><br />
											<?php if($askId == 4 /*Find on the web*/) { ?>
												<label id="toeFindUsUrlShell" style="display: none; clear: both;"><?php echo html::text('find_on_web_url', array('attrs' => 'class="form-control" placeholder="Please, post url"'))?></label>
											<?php } elseif($askId == 5 /*Other way*/) { ?>
												<label style="display: none; clear: both;" id="toeOtherWayTextShell"><?php echo html::textarea('other_way_desc', array('attrs' => 'class="form-control"'))?></label>
											<?php }?>
										<?php }?>
									</div>
								</div>
								<div class="span8 panel panel-default">
									<div class="panel-heading">
										<h4>Check out other useful Wordpress Plugins:</h4>
									</div>
									<div class="panel-body">
										<ul class="bxslider" id="toePluginsSlider">
											<?php foreach($promoPlugins as $pP) { ?>
												<li style="position: relative;">
													<a href="<?php echo $pP['href']?>" target="blank">
														<img src="<?php echo get_template_directory_uri(). '/img/plugin_baners/'. $pP['baner']?>" />
													</a>
													<h2><?php echo $pP['name']?></h2>
												</li>
											<?php }?>
										</ul>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="span12 panel panel-default">
									<div class="panel-heading">
										<h4>Check all <a href="http://readyshoppingcart.com/products_categories/templates/" target="_blank">Free WordPress Themes</a>:</h4>
									</div>
									<div class="panel-body">
										<ul class="bxslider" id="toeTplsSlider">
											<?php 
												$i = 0;
											?>
											<?php foreach($promoTemlates as $pT) { ?>
												<li>
													<center><a href="<?php echo $pT['href']?>" target="_blank" style="text-align: center;"><b><?php echo $pT['name']?></b></a></center><br />
													<a href="<?php echo $pT['href']?>" target="_blank" style="height: 225px; overflow: hidden; width: 300px; display: block; border: 1px black solid;">
														<img style="max-width: 300px;" src="<?php echo get_template_directory_uri(). '/img/tpl_previews/'. $pT['prevImg']?>" />
													</a><br />
													<div style="height: 50px;"><p><?php echo $pT['description']?></p></div><br />
													<div><a href="<?php echo $pT['href']?>" target="_blank" class="button button-primary">Download Now</a></div>
												</li>
											<?php }?>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<span id="toeWelcomePageFindUsMsg"></span>
							<?php echo html::hidden('tplAction', array('value' => $actVal))?>
							<?php echo html::hidden('reqType', array('value' => 'ajax'))?>
							<?php echo html::submit('gonext', array('value' => 'Start use template!', 'attrs' => 'class="button button-primary button-hero"'))?>
						</div>
					</form>
				</div>
			</div>
		</div>
	   <script type="text/javascript">
	   // <!--
	   var toeLoadIconTpl = jQuery('<img />').attr('src', '<?php echo get_template_directory_uri(). '/img/loading-cube.gif'?>');
	   jQuery(document).ready(function(){
		   jQuery('#toeTplWelcomePopup').on('show.bs.modal', function(){
				jQuery('#toePluginsSlider').bxSlider({
					auto: true
				,	mode: 'fade'
				,	captions: true
				,	autoControls: true
				});
				jQuery('#toeTplsSlider').bxSlider({
					auto: true
				,	captions: true
				,	minSlides: 1
				,	maxSlides: 4
				,	slideWidth: 325
				,	slideMargin: 10
				,	moveSlides: 1
				,	autoControls: true
				});
			});
			jQuery('#toeTplWelcomePopup').modal();
			jQuery('#toeWelcomePageFindUsForm input[type=radio][name=where_find_us]').change(function(){
				jQuery('#toeFindUsUrlShell, #toeOtherWayTextShell').hide();
				switch(parseInt(jQuery(this).val())) {
					case 4 /*Find on the web*/ :
						jQuery('#toeFindUsUrlShell').show('fast').css('display', 'block');
						break;
					case 5 /*Other way*/ :
						jQuery('#toeOtherWayTextShell').show('fast');
						break;
				}
			});
			jQuery('#toeWelcomePageFindUsForm').submit(function(){
				jQuery('#toeWelcomePageFindUsMsg').html( toeLoadIconTpl );
				jQuery.ajax({
					url: ajaxurl
				,	data: jQuery(this).serialize()
				,	type: 'POST'
				,	dataType: 'json'
				,	success: function(res) {
						jQuery('#toeWelcomePageFindUsMsg').html('');
						if(res.msg) {
							jQuery('#toeWelcomePageFindUsMsg').html( res.msg );
						}
						setTimeout(function(){
							jQuery('#toeTplWelcomePopup').modal('hide');
						}, 1000);
					}
				});
				return false;
			});
			jQuery('#toeWelcomePageFindUsForm .close').click(function(){
				jQuery( jQuery('<div />').html(toeLoadIconTpl) ).insertBefore(this);
				jQuery('#toeWelcomePageFindUsForm').submit();
				return false;
			});
	   });
	   // -->
	   </script>
			<?php
		}
	}
}
?>